### PR TITLE
obfuscate full token during startup logging

### PR DESCRIPTION
**Pull request by gabemontero**
See https://github.com/openshift/jenkins-openshift-login-plugin/pull/31

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
[merge]

**Comment by jaseemabid** [comment]
@gabemontero Can we make a release with this fixed since this is security critical? I accidentally leaked my osio token a while ago because of this bug.

**Comment by gabemontero** [comment]
On Thu, Mar 1, 2018 at 6:17 AM Jaseem Abid <notifications@github.com> wrote:

> @gabemontero <https://github.com/gabemontero> Can we make a release with
> this fixed since this is security critical? I accidentally leaked my osio
> token a while ago because of this bug.
>
a release of the plugin was made with this change

Or are you talking image update?

Which image / release of the plugin are you using?

**Comment by gabemontero** [comment]
So this change is in v1.0.4 of the openshift login plugin

It will be part of the GA v3.9 openshift jenkins rhel image (coming out later this month)

It is already part of the openshift jenkins centos image

I just submitted https://github.com/openshift/jenkins/pull/517 and https://github.com/openshift/jenkins/pull/518 for 3.6 and 3.7; so they should be in the next errata to go out for those images.

thanks

**Comment by jaseemabid** [comment]
@gabemontero Thanks. Sadly faric8 forked the Jenkins base image so I'll have to add this plugin manually to that version as well.

**Comment by gabemontero** [comment]
On Thu, Mar 1, 2018 at 10:24 AM, Jaseem Abid <notifications@github.com>
wrote:

> @gabemontero <https://github.com/gabemontero> Thanks. Sadly faric8 forked
> the Jenkins base image so I'll have to add this plugin manually to that
> version as well.
>
Yep fully aware .... work has started to some degree with all that (at
least getting their version of the sync plugin
back in line).  But the path won't be short there.

**Pull request merged**
