### PR TITLE
Update README.md - add more detailed instructions with how to use custom role/verb beyond just `view`,`edit`,`admin`

### PR DESCRIPTION
**Pull request by itewk**
The current read me implies that all you need to do to use custom "role"s beyond `admin`, `edit`, and `view` is to create a `Role` and bind users/groups to it. That is not actaully the case. after hours of fighting and digging through code figured out the magic that the plugin isn't actauly looking at Roles it is looking for access to verbs on the `build.openshift.io` groupAPI `jenkins` resource. Which makes sense with the way SubjectAccessRequests work, but really needs to be better documented for the next soul to try and do this.

This is my attempt at clearer documentation.

### CODE REVIEW

**Comment by itewk** [comment]
@otaviof @sbose78 thoughts?

**Comment by itewk** [comment]
ping?

**Comment by itewk** [comment]
ping

**Comment by akram** [comment]
hi @itewk , thank you for reverse engineering this and for the documentation update.
I will merge it now.

**Comment by itewk** [comment]
@akram wahooo. thank you!

**Pull request merged**
