### PR TITLE
Added a place in the logging for "default serviceAccountName"

### PR DESCRIPTION
**Pull request by delgurth**
As pointed out in #133 the logging is currently not complete. This commit fixes that. I'm not sure about the line length. I'm going 1 wider than before... 

Also aligned the formatting and the label for defaultedServerPrefix to "default serverPrefix". Hope that's not a problem.

### CODE REVIEW

**Comment by coreydaley** [comment]
@delgurth Can you please post a sample of the output that this change will produce?

**Comment by coreydaley** [comment]
@delgurth Any updates on this?

**Comment by delgurth** [comment]
> @delgurth Any updates on this?

Sorry. I was trying to use the PR-Testing output. But I was stuck on getting an openshift cluster to run the image on. I wanted to create my own cluster for that purpose, but that's taking too long.

The new output is:

```
2022-08-22 18:00:34 INFO    org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm populateDefaults OpenShift OAuth running in k8s/openshift: [true] with namespace [namespace], ServiceAccount directory [null],
2022-08-22 18:00:34 INFO    org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm populateDefaults      default ServiceAccount directory [/run/secrets/kubernetes.io/serviceaccount], serviceAccountName [null],
2022-08-22 18:00:34 INFO    org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm populateDefaults      default serviceAccountName [jenkins], clientId: [null], default clientID: [system:serviceaccount:namespace:jenkins], clientSecret: [null],
2022-08-22 18:00:34 INFO    org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm populateDefaults      default clientSecret: [eyJhb.......], redirectUrl: [null], default redirectUrl: [https://redirect-url.server.name.anonymized], serverPrefix: [null],
2022-08-22 18:00:34 INFO    org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm populateDefaults      default serverPrefix: [https://kubernetes.default:443]
```

**Comment by delgurth** [comment]
With the last commit the output is now:

```
2022-08-22 18:18:31 INFO    org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm populateDefaults OpenShift OAuth running in k8s/openshift: [true] with namespace [namespace], ServiceAccount directory: [null],
2022-08-22 18:18:31 INFO    org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm populateDefaults      default ServiceAccount directory: [/run/secrets/kubernetes.io/serviceaccount], serviceAccountName: [null],
2022-08-22 18:18:31 INFO    org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm populateDefaults      default serviceAccountName: [jenkins], clientId: [null], default clientID: [system:serviceaccount:namespace:jenkins], clientSecret: [null],
2022-08-22 18:18:31 INFO    org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm populateDefaults      default clientSecret: [eyJhb.......], redirectUrl: [null], default redirectUrl: [https://redirect-url.server.name.anonymized], serverPrefix: [null],
2022-08-22 18:18:31 INFO    org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm populateDefaults      default serverPrefix: [https://kubernetes.default:443]
```

**Pull request merged**
